#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/bspwm"
STYLE=$(cat $DIR/themes/.current)
RASI="$DIR/themes/$STYLE/rofi/powermenu.rasi"
CNFR="$DIR/themes/$STYLE/rofi/confirm.rasi"

# Theme Elements
prompt="$(hostname) ($(echo $DESKTOP_SESSION))"
mesg="Uptime : $(uptime -p | sed -e 's/up //g')"

# Options
layout=$(cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
	option_1=" Lock"
	option_2=" Logout"
	option_3=" Suspend"
	option_4=" Hibernate"
	option_5=" Reboot"
	option_6=" Shutdown"
else
	option_1=""
	option_2=""
	option_3=""
	option_4=""
	option_5=""
	option_6=""
fi
cnflayout=$(cat ${CNFR} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$cnflayout" == 'NO' ]]; then
	yes=' Yes'
	no=' No'
else
	yes=''
	no=''
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Confirmation CMD
confirm_cmd() {
	rofi -dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?' \
		-theme ${CNFR}
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Confirm and execute
confirm_run() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		eval ${@}
	else
		exit
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$option_1)
	swaylock -f
	;;
$option_2)
	confirm_run 'killall Hyprland; pkill -KILL -u $USER'
	;;
$option_3)
	confirm_run 'playerctl pause; swaylock && sleep 1 && hyprctl dispatch dpms off && systemctl hybrid-sleep'
	;;
$option_4)
	confirm_run 'systemctl hibernate'
	;;
$option_5)
	confirm_run 'systemctl reboot'
	;;
$option_6)
	confirm_run 'systemctl poweroff'
	;;
esac
